### ISSUE TITLE
自己的分类数据集使用ImageNet方法切分后，导入paddleX出现以下错误，请问是什么原因呢？

### ISSUE THREAD

**Issue by ksl986735244** [mamingjie-China/split_dataset#3]
数据校验失败！

Traceback (most recent call last):
  File "paddlexui\pms\dataset\operate.py", line 42, in _check_and_copy
  File "paddlexui\pms\dataset\cls_dataset.py", line 34, in check_dataset
  File "paddlexui\pms\dataset\cls_dataset.py", line 67, in check_splited_dataset
  File "paddlexui\pms\dataset\utils.py", line 154, in check_list_txt
Exception: E:\indoor\train_list.txt 格式错误. 列表应包含两列，由空格分离。

**Comment by YouWLiu** [comment]
我也出现了这样的错误，在txt文件中搜索空格的时候也能正确搜索出来。我是这样解决的：手动把txt文件中的每个空格删除再输入后，就可以导入了，用office和记事本的替换功能都不行，只能人工删除再输入，稍微大一点的数据集就很麻烦。
